services:

  templating.loader.drupal:
    public: false
    class: MakinaCorpus\Drupal\Sf\Templating\Loader\DrupalLoader

  templating.loader.filesystem:
    public: false
    class: MakinaCorpus\Drupal\Sf\Templating\Loader\FilesystemLoader

  templating.loader:
    alias: templating.loader.filesystem

  twig.extension.trans:
    public: false
    class: MakinaCorpus\Drupal\Sf\Twig\Extension\TranslationExtension
    tags: [{name: twig.extension}]

  twig.extension.drupal_image:
    public: false
    class: MakinaCorpus\Drupal\Sf\Twig\Extension\DrupalImageExtension
    tags: [{name: twig.extension}]

  twig.extension.drupal_pager:
    public: false
    class: MakinaCorpus\Drupal\Sf\Twig\Extension\DrupalPagerExtension
    tags: [{name: twig.extension}]

  twig.extension.drupal_path:
    public: false
    class: MakinaCorpus\Drupal\Sf\Twig\Extension\DrupalPathExtension
    tags: [{name: twig.extension}]

  twig.extension.drupal_render:
    public: false
    class: MakinaCorpus\Drupal\Sf\Twig\Extension\DrupalRenderExtension
    tags: [{name: twig.extension}]
